services:
  - type: web
    name: django-app
    env: python
    plan: free  # Ensures free tier usage
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn starliftandcontrol.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false  # Ensures the value is not displayed in logs
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DEBUG
        value: "False"  # Boolean (not a string)
